name: php project CI
on:
  push:
    branches: [ "php-dev" ]
  pull_request:
    branches: [ "php-dev" ]
jobs: 
  ImageBuild: 
    runs-on: Linux

    steps:
    - name: perform git code checkout
      uses: actions/checkout@v4

    - name: code host to apache
      run: sudo cp -r $GITHUB.WORKSPACE/gitclassrepo/* /var/www/html

    - name: restart apache
      run: sudo systemctl restart httpd  