name: Nodejs_Project_CI
on:
  push:
    branches: [ "nodejs-project" ]
  pull_request:
    branches: [ "nodejs-project" ]
jobs: 
  ImageBuild: 
    runs-on: Linux

    steps:
    - name: perform git code checkout
      uses: actions/checkout@v4

   # - name: update package using npm 
   #   run: npm ci 

    - name: build node code production 
      run:  npm run build 

    - name: stop containers 
      run:  npm run start &
