name: php project CI
on:
  push:
    branches: [ "php-dev" ]
  pull_request:
    branches: [ "php-dev" ]
jobs: 
  phpdeploy: 
    runs-on: Linux

    steps:
    - name: perform git code checkout
      uses: actions/checkout@v4

    - name: clean path of src
      run: sudo mv /var/www/html/* /var/www/databack

    - name: code host to apache
      run: sudo cp -r $GITHUB_WORKSPACE/src/* /var/www/html/

    - name: restart apache
      run: sudo systemctl restart httpd  